name: Update Jenkins on EC2

on:
  push:
    paths:
      - 'plugins.txt'   # only run when plugins.txt or jenkins.yaml changes
      - 'jenkins.yaml'
  workflow_dispatch:
  # give the job permission to request an OIDC token (Short-lived JWT automatically issued by GitHub for every workflow run. Used to assume an IAM role in AWS without static keys.)
permissions:          
  id-token: write 
  contents: read

jobs:
  update-jenkins:
    runs-on: ubuntu-latest
    steps:
      # Checkout repo
      - name: Checkout
        uses: actions/checkout@v4
        with:
          # Fetch all history to allow for git diff to work correctly on multi-commit pushes.
          fetch-depth: 0 
      # Configure AWS credentials via OIDC
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::058264198774:role/GitHubActionsSSMRole
          aws-region: us-west-2
      # Retrieve Instance ID based on tags
      - name: Get EC2 instance ID
        id: ec2
        run: |
          INSTANCE_ID=$(aws ec2 describe-instances \
            --filters "Name=tag:project,Values=zeus" "Name=instance-state-name,Values=running" \
            --query "Reservations[0].Instances[0].InstanceId" \
            --output text)
          echo "INSTANCE_ID=$INSTANCE_ID" >> $GITHUB_ENV

      - name: Decide and run updates
        env:
          GITHUB_EVENT_BEFORE: ${{ github.event.before }}
          GITHUB_SHA: ${{ github.sha }}
          INSTANCE_ID: ${{ env.INSTANCE_ID }}
        run: |
          echo "Files changed:"
          git diff --name-only "${GITHUB_EVENT_BEFORE}" "${GITHUB_SHA}"

          # run plugins update first if needed
          if git diff --name-only "${GITHUB_EVENT_BEFORE}" "${GITHUB_SHA}" | grep -q "plugins.txt"; then
            SCRIPT="/etc/jenkins/update-jenkins-plugins.sh"
            
            echo "Running $SCRIPT on EC2 instance $INSTANCE_ID"
            COMMAND_ID=$(aws ssm send-command \
              --instance-ids "${INSTANCE_ID}" \
              --document-name "AWS-RunShellScript" \
              --comment "Update Jenkins plugins" \
              --parameters "commands=[\"$SCRIPT\"]" \
              --output text --query "Command.CommandId")
            echo "Command ID: $COMMAND_ID"
            aws ssm wait command-executed \
              --command-id "$COMMAND_ID" \
              --instance-id "$INSTANCE_ID"
            echo "Command Output:"
            aws ssm get-command-invocation \
              --command-id "$COMMAND_ID" \
              --instance-id "$INSTANCE_ID" \
              --query "StandardOutputContent" --output text
            echo "Command Error (if any):"
            aws ssm get-command-invocation \
              --command-id "$COMMAND_ID" \
              --instance-id "$INSTANCE_ID" \
              --query "StandardErrorContent" --output text
          fi

          # then run update config if needed
          if git diff --name-only "${GITHUB_EVENT_BEFORE}" "${GITHUB_SHA}" | grep -q "jenkins.yaml"; then
            SCRIPT="/etc/jenkins/update-jenkins-config.sh"
            
            echo "Running $SCRIPT on EC2 instance $INSTANCE_ID"
            COMMAND_ID=$(aws ssm send-command \
              --instance-ids "${INSTANCE_ID}" \
              --document-name "AWS-RunShellScript" \
              --comment "Update Jenkins config" \
              --parameters "commands=[\"$SCRIPT\"]" \
              --output text --query "Command.CommandId")
            echo "Command ID: $COMMAND_ID"
            aws ssm wait command-executed \
              --command-id "$COMMAND_ID" \
              --instance-id "$INSTANCE_ID"
            echo "Command Output:"
            aws ssm get-command-invocation \
              --command-id "$COMMAND_ID" \
              --instance-id "$INSTANCE_ID" \
              --query "StandardOutputContent" --output text
            echo "Command Error (if any):"
            aws ssm get-command-invocation \
              --command-id "$COMMAND_ID" \
              --instance-id "$INSTANCE_ID" \
              --query "StandardErrorContent" --output text
          fi
